export default [
  {
    ignores: [
      'dist/**',
      'supabase/.branches/**',
    ],
  },
  {
    files: ['**/*.js', '**/*.jsx'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        AbortController: 'readonly',
        Blob: 'readonly',
        BroadcastChannel: 'readonly',
        Deno: 'readonly',
        DOMParser: 'readonly',
        TextEncoder: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        MutationObserver: 'readonly',
        Request: 'readonly',
        ResizeObserver: 'readonly',
        Response: 'readonly',
        URL: 'readonly',
        URLPattern: 'readonly',
        URLSearchParams: 'readonly',
        WebSocket: 'readonly',
        alert: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        cancelAnimationFrame: 'readonly',
        clearImmediate: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        confirm: 'readonly',
        console: 'readonly',
        crypto: 'readonly',
        document: 'readonly',
        fetch: 'readonly',
        global: 'readonly',
        globalThis: 'readonly',
        location: 'readonly',
        localStorage: 'readonly',
        module: 'readonly',
        navigator: 'readonly',
        process: 'readonly',
        queueMicrotask: 'readonly',
        requestAnimationFrame: 'readonly',
        require: 'readonly',
        self: 'readonly',
        sessionStorage: 'readonly',
        setImmediate: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        structuredClone: 'readonly',
        window: 'readonly',
        expect: 'readonly',
        test: 'readonly',
        React: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
      },
    },
    plugins: {
      'react-hooks': {
        rules: {
          'rules-of-hooks': {
            meta: { type: 'problem', docs: { description: 'stub rule' } },
            create: () => ({}),
          },
          'exhaustive-deps': {
            meta: { type: 'suggestion', docs: { description: 'stub rule' } },
            create: () => ({}),
          },
        },
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'off',
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': [
        'warn',
        {
          args: 'none',
          varsIgnorePattern: '^(?:_|React$)',
          argsIgnorePattern: '^_',
        },
      ],
      'no-irregular-whitespace': 'error',
      'no-control-regex': 'warn',
      'no-useless-escape': 'warn',
      'no-empty': [
        'warn',
        {
          allowEmptyCatch: true,
        },
      ],
      'no-debugger': 'error',
      'no-alert': 'off',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'prefer-const': 'warn',
      eqeqeq: ['warn', 'smart'],
      'no-unsafe-finally': 'error',
    },
  },
];
