name: "Refonte: tâche"
description: "Tâche liée à la refonte Alfie Designer"
title: "[Refonte] "
labels: ["refonte","codex"]
body:
  - type: checkboxes
    attributes:
      label: Conformité CDC (cocher avant close)
      options:
        - label: Livraison **PULL** (lien Canva + ZIP), aucune publication automatique. ✔
        - label: Compteurs **images/reels/woofs** visibles, alerte **80 %**. ✔
        - label: Offres/quotas **inchangés** (Starter/Pro/Studio), **1 plan = 1 marque**. ✔
        - label: Stockage **30 jours** par défaut (purge activée). ✔
        - label: Modale **Premium/Woofs** avant toute conso Woof. ✔
  - type: textarea
    attributes:
      label: Notes
      placeholder: Détails, captures, etc.
